function [ F, CE ] = Class2Fitness(KernelFunction,Method,Mode,CrossValidation,ClassLabel,Feature,Type,L,C)


%   Classification analysis with effect number of training
[ Class2Fitness.ErrorMean, Class2Fitness.ErrorFold ] = SVMClassification(...
    KernelFunction,...
    Method,...
    Mode,...
    CrossValidation,...
    ClassLabel,....
    Feature);
for i = 1:length(Class2Fitness.ErrorFold)
    if L == 0
        Class2Fitness.Fitness(i) = FitnessEval(...
            Type,...
            [Class2Fitness.ErrorFold(i,1),Class2Fitness.ErrorFold(i,2)],...
            C);
    else
        Class2Fitness.Fitness(i) = FitnessEval(...
            Type,...
            [Class2Fitness.ErrorFold(i,1),Class2Fitness.ErrorFold(i,2),L],...
            C);
    end
    
end

F   = mean(Class2Fitness.Fitness);
CE  = mean(Class2Fitness.ErrorFold,1);


end

